// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/api/dark.ts";
import * as $3 from "./routes/api/fav.ts";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/api/submitcard.ts";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/logout.ts";
import * as $8 from "./routes/submit.tsx";
import * as $9 from "./routes/tables/[setOfCards].tsx";
import * as $10 from "./routes/user.tsx";
import * as $$0 from "./islands/Card.tsx";
import * as $$1 from "./islands/CardCreator.tsx";
import * as $$2 from "./islands/CardFlipper.tsx";
import * as $$3 from "./islands/CollapsibleNavGroup.tsx";
import * as $$4 from "./islands/DarkModeToggle.tsx";
import * as $$5 from "./islands/LikeButton.tsx";
import * as $$6 from "./islands/MultiSelect.tsx";
import * as $$7 from "./islands/MultiSelectOption.tsx";
import * as $$8 from "./islands/Toggle.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/api/dark.ts": $2,
    "./routes/api/fav.ts": $3,
    "./routes/api/joke.ts": $4,
    "./routes/api/submitcard.ts": $5,
    "./routes/index.tsx": $6,
    "./routes/logout.ts": $7,
    "./routes/submit.tsx": $8,
    "./routes/tables/[setOfCards].tsx": $9,
    "./routes/user.tsx": $10,
  },
  islands: {
    "./islands/Card.tsx": $$0,
    "./islands/CardCreator.tsx": $$1,
    "./islands/CardFlipper.tsx": $$2,
    "./islands/CollapsibleNavGroup.tsx": $$3,
    "./islands/DarkModeToggle.tsx": $$4,
    "./islands/LikeButton.tsx": $$5,
    "./islands/MultiSelect.tsx": $$6,
    "./islands/MultiSelectOption.tsx": $$7,
    "./islands/Toggle.tsx": $$8,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
